### ISSUE TITLE
Add travis automatic test runs

### ISSUE THREAD

**Issue by ddikman** [roccomuso/gtranslate#4]
I can add in so the automated test is run on PR + badge using Travis.

**Comment by ddikman** [comment]
@roccomuso sounds ok? I might need you to add me as an admin on the repo though but I'll have another look if it sounds good.

**Comment by roccomuso** [comment]
yes feel free to do it

**Comment by ddikman** [comment]
@roccomuso seems I do need admin rights in order to do this:
![image](https://user-images.githubusercontent.com/8461739/47970132-23bc2e80-e079-11e8-8546-511ae97f9f74.png)

**Comment by roccomuso** [comment]
enabled
