### ISSUE TITLE
bump package version

### ISSUE THREAD

**Issue by roccomuso** [roccomuso/gtranslate#5]
Once the PRs are merged we can bump and release a new version

**Comment by ddikman** [comment]
I thought that was part of my pr?

**Comment by roccomuso** [comment]
usually it's better to bump separatly and with an explicit commit like `v1.1.0`

**Comment by ddikman** [comment]
I see, it's the npm version. Sure, let's get that separately.

**Comment by ddikman** [comment]
I've opened a PR for the bumped version. Can I publish the new version on NPM as long as I'm a contributor to this repo or do you need to add my account (ddikman) on npm as well?

**Comment by roccomuso** [comment]
added you on npm
